### ISSUE TITLE
Not compatible with new versions of iw

### ISSUE THREAD

**Issue by crabctrl** [sabotage-linux/libnl-tiny#4]
I haven't tested to see which version introduces the breaking change, but the latest stable version of iw uses `NLA_PUT_S32`, which is not present in this fork of libnl-tiny. It seems that OpenWrt's libnl-tiny did recently add the function, however.

**Comment by rofl0r** [comment]
backported all relevant commits of openwrt. pls try master and report back.

**Comment by crabctrl** [comment]
Indeed, iw now builds without issue. Thanks for the quick response!

**Comment by rofl0r** [comment]
cool. let me know if you encounter issues with other packages, i didn't try to use it myself yet.
